server:
  port: 80

logging.level:
  ROOT: WARN

charon:
  retrying:
    max-attempts: 3 # Maximum number of HTTP request forward tries.
    retry-on:
      client-http-error: false # Flag for enabling and disabling triggering HTTP requests forward retries on 4xx HTTP responses from destination.
      server-http-error: true # Flag for enabling and disabling triggering HTTP requests forward retries on 5xx HTTP responses from destination.
      exceptions: java.lang.Exception # Comma-separated list of exceptions that triggers HTTP request forward retries.
  asynchronous-forwarding-thread-pool:
    queue-capacity: 50 # Thread pool executor queue capacity.
    size:
      initial: 5 # Thread pool executor initial number of threads.
      maximum: 30 # Thread pool executor maximum number of threads.
  tracing:
    enabled: false
  mappings:
    - name: telewebion
      path: /telewebion
      destinations: https://sa3.telewebion.com
      asynchronous: false
      retryable: true
    - name: irib
      path: /irib
      destinations: http://cdnlive.irib.ir
      asynchronous: false
      retryable: true

spring:
  banner:
    location: banner.txt

telewebion:
  channels:
    - name: "tv1"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/tv1.png"
    - name: "tv2"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/tv2.png"
    - name: "tv3"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/tv3.png"
    - name: "tv4"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/tv4.png"
    - name: "tehran"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/tehran.png"
    - name: "irinn"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/irinn.png"
    - name: "shijam"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/shijam.png"
    - name: "nasim"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/nasim.png"
    - name: "shinama"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/shinama.png"
    - name: "varzesh"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/varzesh.png"
    - name: "pooya"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/pooya.png"
    - name: "ifilm"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/ifilm.png"
    - name: "shinamak"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/shinamak.png"
    - name: "namayesh"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/namayesh.png"
    - name: "sepehr"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/sepehr.png"
    - name: "shiran"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/shiran.png"
    - name: "mostanad"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/mostanad.png"
    - name: "amouzesh"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/amouzesh.png"
    - name: "quran"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/quran.png"
    - name: "salamat"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/salamat.png"
    - name: "jjtv1"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/jjtv1.png"
    - name: "hdtest"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/hdtest.png"
    - name: "omid"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/omid.png"
    - name: "ofogh"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/ofogh.png"
    - name: "shoma"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/shoma.png"
    - name: "esfahan"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/esfahan.png"
    - name: "sahand"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/sahand.png"
    - name: "fars"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/fars.png"
    - name: "khoozestan"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/khoozestan.png"
    - name: "khorasanrazavi"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/khorasanrazavi.png"
    - name: "kordestan"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/kordestan.png"
    - name: "baran"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/baran.png"
    - name: "semnan"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/semnan.png"
    - name: "aftab"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/aftab.png"
    - name: "aflak"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/aflak.png"

irib:
  channels:
    - name: "tv1"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123487"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/tv1.png"
    - name: "tv2"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123488"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/tv2.png"
    - name: "tv3"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123489"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/tv3.png"
    - name: "tv4"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123490"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/tv4.png"
    - name: "tehran"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123491"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/tehran.png"
    - name: "irinn"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123492"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/irinn.png"
    - name: "amouzesh"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123493"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/amouzesh.png"
    - name: "quran"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123494"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/quran.png"
    - name: "mostanad"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123495"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/mostanad.png"
    - name: "namayesh"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123498"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/namayesh.png"
    - name: "ofogh"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123499"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/ofogh.png"
    - name: "varzesh"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123503"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/varzesh.png"
    - name: "pouya"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123485"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/pooya.png"
    - name: "salamat"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123504"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/salamat.png"
    - name: "nasim"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123505"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/nasim.png"
    - name: "tamasha"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123525"
      logo: ""
    - name: "omid-tv"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123560"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/omid.png"
    - name: "shoma"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123496"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/shoma.png"
    - name: "iran-kala"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123497"
      logo: ""
    - name: "shinamak"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123657"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/shinamak.png"
    - name: "shinama"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123615"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/shinama.png"
    - name: "shiran"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123652"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/shiran.png"
    - name: "shijam"
      address: "http://live.irib.ir/?idc=C0&idb=TV&nol=123658"
      logo: "https://static.televebion.net/web/content_images/channel_images/thumbs/new/240/v4/shijam.png"
